name: Deploy to Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up environment variables
        env:
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: |
          echo "DATABASE_ID=$DATABASE_ID" >> .env
          echo "NOTION_API_KEY=NOTION_API_KEY" >> .env
          echo "PAGE_ID=PAGE_ID" >> .env
          echo "TG_TOKEN=TG_TOKEN" >> .env

      - name: Execute update-env.sh
        run: ./update-env.sh
