name: Deploy to Docker Compose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
            images: georgepasyuk/notion-tg

      - name: Load .env file
        run: echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" > .env && echo "DATABASE_ID=${{ secrets.DATABASE_ID }}" >> .env && echo "PAGE_ID=${{ secrets.PAGE_ID }}" >> .env && echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" >> .env

      - name: Execute update-env.sh
        run: ./update-env.sh

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

